version: '3'

services:
  ursim:
    image: universalrobots/ursim_e-series
    ports:
      - 6080:6080
    environment:
      - ROBOT_MODEL=UR10
    networks:
      ursim_net:
        ipv4_address: 192.168.56.101

  ur-driver:
    image: ur-driver:latest
    environment:
      - ROBOT_IP=192.168.56.101
    networks:
      ursim_net:
        ipv4_address: 192.168.56.102
    depends_on:
      - ursim

networks:
  ursim_net:
    ipam:
      config:
        - subnet: 192.168.56.0/24
