name: push_t
mode: inference
seed: 4077

action_dict: ['ee_pose']  # possible values: ee_pose
obs_dict: ['state']  # possible values: state, img, keypoint, n_contacts

network:
  use_transformer: False

train:
  num_epochs: 100
  dataset_path: "./data/push_t_data.zarr"

inference:
  max_steps: 200
  render: True
  checkpoint_path: "./checkpoints/push_t.pt"

parameters:
  num_diffusion_iters: 100

  # Diffusion horizons
  pred_horizon: 16
  obs_horizon: 2
  action_horizon: 8
