name: ur10
mode: inference
seed: 4077

controller: movel  # possible values: movel, joints
action_dict: ['position', 'rotation_6d']  # possible values: position, rotation_6d
obs_dict: ['ee_position', 'ee_rotation_6d']  # possible values: joint_pos, joint_vel, joint_eff, ee_position, ee_rotation_6d

train:
  num_epochs: 100
  dataset_path: "./data/ur10/ur10.zarr"

inference:
  max_steps: 225
  render: False
  checkpoint_path: "./checkpoints/diffusion_policy.pt"

parameters:
  num_diffusion_iters: 10

  # Diffusion horizons
  pred_horizon: 16
  obs_horizon: 2
  action_horizon: 8
