name: ur10
mode: inference
seed: 4077

controller: joints  # possible values: joints
action_list: ['commanded_ee_position_xy']  # possible values: commanded_ee_position, commanded_ee_rotation_6d, commanded_joints
obs_list: ['ee_position_xy', 'torque2']  # possible values: joint_pos, joint_vel, joint_eff, ee_position, ee_rotation_6d, force, torque
keypoints_in_obs: True

use_transformer: False

model_name: test2

transformer_args:
  n_layer: 8
  n_head: 4
  n_emb: 256
  p_drop_emb: 0.0
  p_drop_attn: 0.01

  causal_attn: True
  time_as_cond: True # if false, use BERT like encoder only arch, time as input
  obs_as_cond: True
  n_cond_layers: 2 # >0: use transformer encoder for cond, otherwise use MLP

unet_args:
  diffusion_step_embed_dim: 256
  down_dims: [256, 512, 1024]
  kernel_size: 5
  n_groups: 8

train:
  num_epochs: 2000
  dataset_path: ./data/ur10/cube_alt.zarr

inference:
  num_inferences: 25
  max_steps: 1000
  render: False
  checkpoint_path: None
  simulator: isaacsim  # possible values: isaacsim
  warmstart: True

parameters:
  num_diffusion_iters: 45

  # Diffusion horizons
  pred_horizon: 20
  obs_horizon: 3
  action_horizon: 10

keypoint_args:
  num_keypoints: 7
  min_dist: 0.04
  threshold_force: 1.0
