name: ur10
mode: inference
seed: 4077

controller: joints  # possible values: movel, joints
action_list: ['commanded_ee_position', 'commanded_ee_rotation_6d']  # possible values: position, rotation_6d
obs_list: ['ee_position', 'ee_rotation_6d']  # possible values: joint_pos, joint_vel, joint_eff, ee_position, ee_rotation_6d
keypoints_in_obs: False

use_transformer: True

transformer_args:
  n_layer: 8
  n_head: 4
  n_emb: 256
  p_drop_emb: 0.0
  p_drop_attn: 0.01

  causal_attn: True
  time_as_cond: True # if false, use BERT like encoder only arch, time as input
  obs_as_cond: True
  n_cond_layers: 0 # >0: use transformer encoder for cond, otherwise use MLP

unet_args: {}  # use defaults

train:
  num_epochs: 100
  dataset_path: "./data/ur10/ur10_heart.zarr"

inference:
  num_inferences: 2
  max_steps: 225
  render: False
  checkpoint_path: "./checkpoints/ur10_heart.pt"
  simulator: isaacsim  # possible values: ursim, isaacsim
  warmstart: True

parameters:
  num_diffusion_iters: 10

  # Diffusion horizons
  pred_horizon: 16
  obs_horizon: 2
  action_horizon: 3
